Arrange exit codes (fix #25)
greymd/ttcopy pull request #31
Opened 2017-02-03 09:17 UTC by mecab

2017-02-03 11:41 UTC, greymd commented
cool changes!

and sorry for Japanese.

いままで関数の中で`exit`呼ぶのを意図的に避けてると思ってたｗ
たとえば、`ttcopy`コマンドで有り得る終了条件は全て`ttcopy.sh`に記述したほうが、メンテ性が高いという意図があったのかと。

まあ、そんな大きなプログラムでもないし、コレはコレでとても良いと思います。

ということで`__ttcp::opts` 関数内の例外も`return`ではなくそのまま`exit`して良いのではと思った。
`return 254`のところは`exit 0`にしちゃてですね。。

2017-02-04 04:18 UTC, greymd requested changes
Excuse me, let me make some changes to this PR.

2017-02-04 04:31 UTC, greymd approved these changes
I made some changes. Is it ok for @mecab  ?

2017-02-05 12:33 UTC, mecab commented
Sorry, I was thinking about which is better that we should exit immediately or exit in the main.

Anyway thank you for editing PR. Working is the best 😆

2017-02-05 12:34 UTC, merged